apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: order_service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5004
            - containerPort: 8000  # Port for Prometheus to scrape metrics
          env:
            - name: DATABASE_URL
              value: "postgresql://auth_user:auth_password@postgres:5432/auth_db"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
spec:
  selector:
    app: order-service
  ports:
    - name: http
      protocol: TCP
      port: 5004
      targetPort: 5004
    - name: metrics
      protocol: TCP
      port: 8000  # Port to expose metrics endpoint
      targetPort: 8000
  type: ClusterIP
