apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          imagePullPolicy: IfNotPresent
          image: product_service:latest
          ports:
            - containerPort: 5001
            - containerPort: 8000  # Port for Prometheus to scrape metrics
          env:
            - name: DATABASE_URL
              value: "postgresql://auth_user:auth_password@postgres:5432/auth_db"
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
spec:
  selector:
    app: product-service
  ports:
    - name: http
      protocol: TCP
      port: 5001
      targetPort: 5001
    - name: metrics
      protocol: TCP
      port: 8000  # Port to expose metrics endpoint
      targetPort: 8000
  type: ClusterIP
