apiVersion: apps/v1
kind: Deployment
metadata:
  name: view-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: view-service
  template:
    metadata:
      labels:
        app: view-service
    spec:
      containers:
      - name: view-service
        image: view_service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        - containerPort: 8000  # Port for Prometheus to scrape metrics
        env:
          - name: FLASK_APP
            value: "main.py"
        # Ensure you specify the correct environment variables if needed
---
apiVersion: v1
kind: Service
metadata:
  name: view-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
spec:
  selector:
    app: view-service
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
    - name: metrics
      protocol: TCP
      port: 8000  # Port to expose metrics endpoint
      targetPort: 8000
  type: ClusterIP
