apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: auth_service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5003
        - containerPort: 8000  # Port for Prometheus to scrape metrics
        env:
        - name: FLASK_APP
          value: "main.py"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
spec:
  selector:
    app: auth-service
  ports:
    - name: http
      protocol: TCP
      port: 5003
      targetPort: 5003
    - name: metrics
      protocol: TCP
      port: 8000  # Port to expose metrics endpoint
      targetPort: 8000
  type: ClusterIP
